spring.application.name=movie-api
spring.datasource.url=jdbc:h2:mem:moviedb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
csv.file.path=data/movielist.csv